.PHONY: clean All

All:
	@echo "----------Building project:[ cipher - Debug ]----------"
	@cd "/home/stud/C++Projects/CryptoProg/cipher/cipher" && "$(MAKE)" -f  "cipher.mk"
clean:
	@echo "----------Cleaning project:[ cipher - Debug ]----------"
	@cd "/home/stud/C++Projects/CryptoProg/cipher/cipher" && "$(MAKE)" -f  "cipher.mk" clean
